In [1]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import os, glob

In [2]:
cd ~/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/

/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs

In [3]:
ls -all

total 16360
drwxr-xr-x  28 Theo  staff      896 Mar 11 16:10 ./
drwxr-xr-x  10 Theo  staff      320 Mar 12 00:49 ../
-rw-r--r--   1 Theo  staff   782911 Mar 11 16:10 Fond_10a_base_nominative_a.csv
-rw-r--r--   1 Theo  staff  1212485 Mar 11 16:10 Fond_10a_base_nominative_b.csv
-rw-r--r--   1 Theo  staff   478787 Mar 11 16:10 Fond_10a_base_nominative_c.csv
-rw-r--r--   1 Theo  staff   561939 Mar 11 16:10 Fond_10a_base_nominative_d.csv
-rw-r--r--   1 Theo  staff   144304 Mar 11 16:10 Fond_10a_base_nominative_e.csv
-rw-r--r--   1 Theo  staff   263319 Mar 11 16:10 Fond_10a_base_nominative_f.csv
-rw-r--r--   1 Theo  staff   421143 Mar 11 16:10 Fond_10a_base_nominative_g.csv
-rw-r--r--   1 Theo  staff   367663 Mar 11 16:10 Fond_10a_base_nominative_h.csv
-rw-r--r--   1 Theo  staff    42660 Mar 11 16:10 Fond_10a_base_nominative_i.csv
-rw-r--r--   1 Theo  staff   101261 Mar 11 16:10 Fond_10a_base_nominative_j.csv
-rw-r--r--   1 Theo  staff   283165 Mar 11 16:10 Fond_10a_base_nominative_k.csv
-rw-r--r--   1 Theo  staff   532977 Mar 11 16:10 Fond_10a_base_nominative_l.csv
-rw-r--r--   1 Theo  staff   995979 Mar 11 16:10 Fond_10a_base_nominative_m.csv
-rw-r--r--   1 Theo  staff   121701 Mar 11 16:10 Fond_10a_base_nominative_n.csv
-rw-r--r--   1 Theo  staff    89936 Mar 11 16:10 Fond_10a_base_nominative_o.csv
-rw-r--r--   1 Theo  staff   303139 Mar 11 16:10 Fond_10a_base_nominative_p.csv
-rw-r--r--   1 Theo  staff    16554 Mar 11 16:10 Fond_10a_base_nominative_q.csv
-rw-r--r--   1 Theo  staff   358993 Mar 11 16:10 Fond_10a_base_nominative_r.csv
-rw-r--r--   1 Theo  staff   568287 Mar 11 16:10 Fond_10a_base_nominative_s.csv
-rw-r--r--   1 Theo  staff   273635 Mar 11 16:10 Fond_10a_base_nominative_t.csv
-rw-r--r--   1 Theo  staff    14666 Mar 11 16:10 Fond_10a_base_nominative_u.csv
-rw-r--r--   1 Theo  staff   172143 Mar 11 16:10 Fond_10a_base_nominative_v.csv
-rw-r--r--   1 Theo  staff    86323 Mar 11 16:10 Fond_10a_base_nominative_w.csv
-rw-r--r--   1 Theo  staff     3129 Mar 11 16:10 Fond_10a_base_nominative_x.csv
-rw-r--r--   1 Theo  staff    34685 Mar 11 16:10 Fond_10a_base_nominative_y.csv
-rw-r--r--   1 Theo  staff    85389 Mar 11 16:10 Fond_10a_base_nominative_z.csv

In [4]:
# importing csvs one by one trail
db0 = pd.read_csv("Fond_10a_base_nominative_a.csv", encoding='UTF-8', engine="python", sep = ";")

db0

,id_conflit_intitule,id_sous_conflit_intitule,id_famille_cote_intitule,sous_serie,serie,article,nom,prenom,nom_autre,pseudonyme,...,disparition_date_libre,disparition_jour_mois_annee,jdd_jour_mois_annee,disparition_lieu_complement,id_disparition_lieu_intitule,id_disparition_departement_intitule,id_disparition_pays_intitule,id_tgi_lieu_intitule,id_tgi_departement_intitule,id_tgi_pays_intitule
0,Théâtres d'opérations extérieurs,Afrique du Nord,NaN,NaN,NaN,NaN,AB EL OUAHAB BEN SAID BEN BELGACEM,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4063.0,ABABOA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4063.0,ABABOU,Abdelkader,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4034.0,ABABSA,Belgacem,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4034.0,ABABSIA OTHMANE BEN AHMED,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4064.0,AZZOUT,Saïd,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1912,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4064.0,AZZOUZ,Mokhtar,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1913,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4036.0,AZZOUZ,Ahmed,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1914,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4036.0,AZZOUZ BEN MOHAMED,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1915,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4064.0,AZZOUZ MOHAMMED OULD KADDOUR OULD KADDOUR BEN ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Making a loop statement to create all the dataframes from the csv files
path = "/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/"
all_files = glob.glob(path + "*.csv")

In [6]:
all_files

['/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_a.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_v.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_w.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_b.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_u.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_t.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_c.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_p.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_g.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_f.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_q.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_s.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_d.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_e.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_r.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_h.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_i.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_k.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_j.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_n.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_y.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_x.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_o.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_m.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_z.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_l.csv']

In [7]:
li = [pd.read_csv(filename, encoding='UTF-8', engine="python", sep = ";") for filename in all_files]
db = pd.concat(li, axis = 0, ignore_index = True)

In [8]:
db

,id_conflit_intitule,id_sous_conflit_intitule,id_famille_cote_intitule,sous_serie,serie,article,nom,prenom,nom_autre,pseudonyme,...,disparition_date_libre,disparition_jour_mois_annee,jdd_jour_mois_annee,disparition_lieu_complement,id_disparition_lieu_intitule,id_disparition_departement_intitule,id_disparition_pays_intitule,id_tgi_lieu_intitule,id_tgi_departement_intitule,id_tgi_pays_intitule
0,Théâtres d'opérations extérieurs,Afrique du Nord,NaN,NaN,NaN,NaN,AB EL OUAHAB BEN SAID BEN BELGACEM,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4063.0,ABABOA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4063.0,ABABOU,Abdelkader,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4034.0,ABABSA,Belgacem,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4034.0,ABABSIA OTHMANE BEN AHMED,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20054,Théâtres d'opérations extérieurs,Afrique du Nord,NaN,NaN,NaN,NaN,LUZET,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20055,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4070.0,LVOFF,André,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20056,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4046.0,LYARID BEN FARRADJ,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20057,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4046.0,LYAZID BEL FKI AOMAR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20058,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4070.0,LYSRI,Youcef,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN