In [14]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import os, glob

In [2]:
cd ~/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/

/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs

In [3]:
# Making a loop statement to create all the dataframes from the csv files
path = "/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/"
all_files = glob.glob(path + "*.csv")

In [4]:
all_files

['/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_a.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_v.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_w.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_b.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_u.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_t.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_c.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_p.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_g.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_f.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_q.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_s.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_d.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_e.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_r.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_h.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_i.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_k.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_j.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_n.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_y.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_x.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_o.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_m.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_z.csv',
 '/Users/Theo/dev/projetMemoire/militaires-decedes-sur-les-theatres-d-operations-exterieurs/Fond_10a_base_nominative_l.csv']

In [5]:
li = [pd.read_csv(filename, encoding='UTF-8', engine="python", sep = ";") for filename in all_files]
db = pd.concat(li, axis = 0, ignore_index = True)

In [6]:
db

,id_conflit_intitule,id_sous_conflit_intitule,id_famille_cote_intitule,sous_serie,serie,article,nom,prenom,nom_autre,pseudonyme,...,disparition_date_libre,disparition_jour_mois_annee,jdd_jour_mois_annee,disparition_lieu_complement,id_disparition_lieu_intitule,id_disparition_departement_intitule,id_disparition_pays_intitule,id_tgi_lieu_intitule,id_tgi_departement_intitule,id_tgi_pays_intitule
0,Théâtres d'opérations extérieurs,Afrique du Nord,NaN,NaN,NaN,NaN,AB EL OUAHAB BEN SAID BEN BELGACEM,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4063.0,ABABOA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4063.0,ABABOU,Abdelkader,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4034.0,ABABSA,Belgacem,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4034.0,ABABSIA OTHMANE BEN AHMED,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20054,Théâtres d'opérations extérieurs,Afrique du Nord,NaN,NaN,NaN,NaN,LUZET,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20055,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4070.0,LVOFF,André,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20056,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4046.0,LYARID BEN FARRADJ,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20057,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4046.0,LYAZID BEL FKI AOMAR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20058,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4070.0,LYSRI,Youcef,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
clean1db = db.dropna(axis=1, how="all", thresh=None, subset=None, inplace=False)

In [17]:
clean1db.columns

Index(['id_conflit_intitule', 'id_sous_conflit_intitule',
       'id_famille_cote_intitule', 'sous_serie', 'serie', 'article', 'nom',
       'prenom', 'nom_autre', 'pseudonyme', 'naissance_jour_mois_annee',
       'id_naissance_lieu_intitule', 'id_naissance_departement_intitule',
       'id_naissance_pays_intitule', 'id_statut_intitule',
       'id_mention_intitule', 'classe', 'recrutement_matricule',
       'id_recrutement_bureau_intitule', 'id_grade_intitule',
       'id_unite_intitule', 'id_bataillon_intitule', 'id_compagnie_intitule',
       'id_batterie_intitule', 'detail_unite', 'id_profession_intitule',
       'deces_jour_mois_annee', 'id_deces_lieu_intitule',
       'id_deces_departement_intitule', 'id_deces_pays_intitule',
       'id_operation_intitule', 'id_transcription_etablissement_lieu_intitule',
       'id_transcription_etablissement_departement_intitule',
       'id_transcription_etablissement_pays_intitule',
       'id_dernier_domicile_lieu_intitule',
       'id_dernier_domicile_departement_intitule',
       'id_dernier_domicile_pays_intitule', 'id_sepulture_lieu_intitule',
       'id_sepulture_departement_intitule', 'id_sepulture_pays_intitule',
       'id_sepulture_nom_du_site_intitule', 'id_sepulture_type_intitule',
       'sepulture_tombe_individuelle_numero', 'sources', 'deportation',
       'decoration_posthume', 'rehabilitation', 'lien_ark_fiche',
       'corps_retrouve', 'disparition_jour_mois_annee', 'jdd_jour_mois_annee'],
      dtype='object')

In [18]:
unwantedcol = ['pseudonyme','id_batterie_intitule','id_compagnie_intitule','id_dernier_domicile_lieu_intitule',
               'id_dernier_domicile_departement_intitule','id_dernier_domicile_pays_intitule','id_sepulture_lieu_intitule',
       'id_sepulture_departement_intitule', 'id_sepulture_pays_intitule',
       'id_sepulture_nom_du_site_intitule', 'id_sepulture_type_intitule',
       'sepulture_tombe_individuelle_numero']

In [19]:
clean1db.drop(unwantedcol,axis=1)

,id_conflit_intitule,id_sous_conflit_intitule,id_famille_cote_intitule,sous_serie,serie,article,nom,prenom,nom_autre,naissance_jour_mois_annee,...,id_transcription_etablissement_departement_intitule,id_transcription_etablissement_pays_intitule,sources,deportation,decoration_posthume,rehabilitation,lien_ark_fiche,corps_retrouve,disparition_jour_mois_annee,jdd_jour_mois_annee
0,Théâtres d'opérations extérieurs,Afrique du Nord,NaN,NaN,NaN,NaN,AB EL OUAHAB BEN SAID BEN BELGACEM,NaN,NaN,0000-00-00,...,NaN,NaN,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
1,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4063.0,ABABOA,NaN,NaN,NaN,...,NaN,Algérie,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
2,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4063.0,ABABOU,Abdelkader,NaN,NaN,...,NaN,Algérie,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
3,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4034.0,ABABSA,Belgacem,NaN,NaN,...,NaN,Algérie,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
4,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4034.0,ABABSIA OTHMANE BEN AHMED,NaN,NaN,NaN,...,NaN,Algérie,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20054,Théâtres d'opérations extérieurs,Afrique du Nord,NaN,NaN,NaN,NaN,LUZET,NaN,NaN,NaN,...,NaN,NaN,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
20055,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4070.0,LVOFF,André,NaN,1899-00-00,...,75 - Paris (ex Seine),NaN,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
20056,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4046.0,LYARID BEN FARRADJ,NaN,NaN,NaN,...,NaN,NaN,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
20057,Théâtres d'opérations extérieurs,Afrique du Nord,AC,40.0,R,4046.0,LYAZID BEL FKI AOMAR,NaN,NaN,NaN,...,NaN,NaN,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN
20058,Théâtres d'opérations extérieurs,Levant,AC,40.0,R,4070.0,LYSRI,Youcef,NaN,NaN,...,NaN,Algérie,"Service historique de la Défense, Caen",0,0,0,https://www.memoiredeshommes.sga.defense.gouv....,0,NaN,NaN